{{- if and .Values.app.enabled .Values.app.envSecret }}
{{- $hasSimpleSecrets := false }}
{{- range $key, $val := .Values.app.envSecret }}
{{- if kindIs "string" $val }}
{{- $hasSimpleSecrets = true }}
{{- end }}
{{- end }}
{{- if $hasSimpleSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mes-agents.fullname" . }}-env
  labels:
    {{- include "mes-agents.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.app.envSecret }}
  {{- if kindIs "string" $val }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
